version: '3'

services:
  auth-ms:
    container_name: 'auth-ms'
    build: ./auth-ms/
    command: python main.py
    restart: always
    env_file:
      - ./.env
    ports:
      - 5000:5000
    depends_on:
      - postgresql
  postgresql:
    container_name: 'postgresql'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
