tasks = [
    {
        "theme": "Поиск номера телефона",
        "task_description": "Найдите все номера телефонов в формате (XXX) XXX-XXXX из данного текста",
        "text": "I need to contact my friend, his phone number is (123) 456-7890. I also have the number of the pizza place, it is (234) 567-8901. Finally, I have the number of my dentist, which is (345) 678-9012.",
        "expected_result": "(123) 456-7890, (234) 567-8901, (345) 678-9012",
    },
    {
        "theme": "Поиск номера телефона",
        "task_description": "Найдите все номера телефонов в формате XXX-XXX-XXXX из данного текста",
        "text": "Here are a few phone numbers to contact us: 123-456-7890, 234-567-8901, and 345-678-9012.",
        "expected_result": "123-456-7890, 234-567-8901, 345-678-9012",
    },
    {
        "theme": "Поиск номера телефона",
        "task_description": "Найдите все номера телефонов в формате (XXX) XXX-XXXX или XXX-XXX-XXXX из данного текста",
        "text": "Please contact us at either (123) 456-7890 or 234-567-8901. Our fax number is (345) 678-9012.",
        "expected_result": "(123) 456-7890, 234-567-8901, 345-678-9012",
    },
    {
        "theme": "Поиск времени",
        "task_description": "Найдите все время в формате HH:MM из данного текста",
        "text": "The meeting will start at 10:30 AM. Lunch is scheduled for 12:00 PM. The afternoon session will begin at 1:30 PM.",
        "expected_result": "10:30, 12:00, 1:30",
    },
    {
        "theme": "Поиск времени",
        "task_description": "Найдите все время в формате H:MM или HH:MM из данного текста",
        "text": "The first train leaves at 6:00 AM, and the last train departs at 9:30 PM.",
        "expected_result": "6:00, 9:30, AM, PM",
    },
    {
        "theme": "Поиск времени",
        "task_description": "Найдите все время в формате H:MM или HH:MM из данного текста, но только те, которые содержат время после 6 PM",
        "text": "The store is open from 9:00 AM to 9:00 PM. Please arrive before 6 PM to place your order.",
        "expected_result": "9:00, PM",
    },
    {
        "theme": "Поиск email",
        "task_description": "Найдите все email в формате name.surname@domain.com или initials.surname@domain.com",
        "text": "Вчера я общался с John Doe из компании Example Inc. Мне нужно было отправить ему письмо на его рабочий email адрес john.doe@example.com. Также я обнаружил, что еще несколько сотрудников компании Example Inc имеют похожие email адреса, например, j.smith@example.com и s.garcia@example.com.",
        "expected_result": "john.doe@example.com, j.smith@example.com, s.garcia@example.com",
    },
    {
        "theme": "Поиск email",
        "task_description": "Найдите все email в формате firstname.lastname@domain.com или firstname_initial.lastname@domain.com",
        "text": "На прошлой неделе я посетил конференцию, где я познакомился с участниками из разных компаний. Один из них была Kate Jones из компании Example Co. Мы обменялись контактами, и я получил ее email адрес kate.jones@example.com. Я также узнал, что другие участники имеют подобные email адреса, например, s.gonzalez@example.com и r.flores@example.com.",
        "expected_result": "kate.jones@example.com, s.gonzalez@example.com, r.flores@example.com",
    },
    {
        "theme": "Поиск email",
        "task_description": "Найдите все email в формате randomstring@domain.com или randomstring+anythingelse@domain.com",
        "text": "Сегодня я зарегистрировался на нескольких сайтах и использовал различные email адреса для регистрации. Некоторые из них были stefany39@example.com, bobcool@example.com и davidh+support@example.com. На одном сайте мне даже предложили использовать email адрес с дополнительным фрагментом после знака '+' для лучшей организации почты.",
        "expected_result": "stefany39@example.com, bobcool@example.com, davidh+support@example.com",
    },
    {
        "theme": "hex_color",
        "task_description": "Найдите все HEX-цвета в тексте",
        "text": "Фоновый цвет #f2f2f2, текстовый цвет #333333, цвет акцента #f44336",
        "expected_result": "#f2f2f2, #333333, #f44336",
    },
    {
        "theme": "hex_color",
        "task_description": "Найдите все шестнадцатеричные цвета в CSS-стилях",
        "text": ".button { background-color: #fff; border: 1px solid #ccc; color: #333; }",
        "expected_result": "#fff, #ccc, #333",
    },
    {
        "theme": "hex_color",
        "task_description": "Найдите все шестнадцатеричные цвета в HTML-коде",
        "text": '<div style="background-color: #f2f2f2; color: #333333;">Текст с заданными цветами</div>',
        "expected_result": "#f2f2f2, #333333",
    },
    {
        "theme": "url",
        "task_description": "Найдите все URL в тексте",
        "text": "Посетите наш сайт: https://example.com или страницу с контактами: https://example.com/contacts",
        "expected_result": "https://example.com, https://example.com/contacts",
    },
    {
        "theme": "url",
        "task_description": "Найдите все ссылки на страницы внутри домена example.com",
        "text": "Ссылка на главную страницу: https://example.com, ссылка на страницу с информацией: https://example.com/about, ссылка на страницу новостей: https://example.com/news",
        "expected_result": "https://example.com, https://example.com/about, https://example.com/news",
    },
    {
        "theme": "url",
        "task_description": "Найдите все URL, которые начинаются со слова 'http'",
        "text": "Ссылка на наш сайт: http://example.com, ссылка на наш аккаунт в социальной сети: https://vk.com/example, ссылка на статью: https://example.com/article",
        "expected_result": "http://example.com, https://example.com/article",
    },
    {
        "theme": "ip",
        "task_description": "Найдите IP-адрес в тексте",
        "text": "IP-адрес моего компьютера - 192.168.0.1",
        "expected_result": "192.168.0.1",
    },
    {
        "theme": "ip",
        "task_description": "Найдите все IP-адреса в тексте",
        "text": "В данном тексте присутствуют следующие IP-адреса: 192.168.0.1, 10.0.0.1, 172.16.0.1",
        "expected_result": "192.168.0.1, 10.0.0.1, 172.16.0.1",
    },
    {
        "theme": "ip",
        "task_description": "Найдите IP-адреса, которые начинаются с цифры 2",
        "text": "IP-адрес моего компьютера - 192.168.0.1, IP-адрес маршрутизатора - 10.0.0.1, IP-адрес сервера - 23.45.67.89",
        "expected_result": "192.168.0.1, 23.45.67.89",
    },
    {
        "theme": "credit_card",
        "task_description": "Найдите номер кредитной карты в тексте",
        "text": "Мой номер кредитной карты 1234-5678-9012-3456",
        "expected_result": "1234-5678-9012-3456",
    },
    {
        "theme": "credit_card",
        "task_description": "Найдите все номера кредитных карт в тексте",
        "text": "В данном тексте присутствуют следующие номера кредитных карт: 1234-5678-9012-3456, 9876-5432-1098-7654, 5555-5555-5555-4444",
        "expected_result": "1234-5678-9012-3456, 9876-5432-1098-7654, 5555-5555-5555-4444",
    },
    {
        "theme": "credit_card",
        "task_description": "Найдите номера кредитных карт, которые начинаются с цифры 5 и заканчиваются на 9",
        "text": "Мой номер кредитной карты - 5123-4567-8901-2395, номер карты моего друга - 5555-5555-5555-4449, номер карты моего банка - 4111-1111-1111-1111",
        "expected_result": "5555-5555-5555-4449",
    },
    {
        "theme": "Поиск почтовых индексов",
        "task_description": "Найдите почтовый индекс в тексте",
        "text": "Адрес доставки: ул. Пушкина, дом 10, кв. 5, г. Москва, 123456",
        "expected_result": "123456",
    },
    {
        "theme": "Поиск почтовых индексов",
        "task_description": "Найдите почтовый индекс в тексте",
        "text": "Пожалуйста, отправьте письмо на адрес: ул. Ленина, д. 5, г. Краснодар, 350000",
        "expected_result": "350000",
    },
    {
        "theme": "Поиск почтовых индексов",
        "task_description": "Найдите почтовый индекс в тексте",
        "text": "Мы находимся в г. Санкт-Петербург, ул. Невский проспект, дом 28, 191186",
        "expected_result": "191186",
    },
]
print(tasks)
